import "../styles/globals.css";
import type { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";
import { GlobalStyles, MantineProvider, NormalizeCSS } from "@mantine/core";
import { NextPage } from "next/types";
import { ReactElement, ReactNode } from "react";
import Head from "next/head";
import { NotificationsProvider } from "@mantine/notifications";

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page: any) => page);

  return (
    <>
      <Head>
        <title>{Component.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={pageProps?.session} refetchInterval={5 * 60}>
        <MantineProvider
          theme={{
            fontFamily: "Verdana, sans-serif",
            fontFamilyMonospace: "Monaco, Courier, monospace",
            headings: { fontFamily: "Greycliff CF, sans-serif" },
            loader: "bars",
          }}
        >
          <NormalizeCSS />
          <GlobalStyles />
          <NotificationsProvider>
            {getLayout(<Component {...pageProps} />)}
          </NotificationsProvider>
        </MantineProvider>
      </SessionProvider>
    </>
  );
}

export default MyApp;

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
  title?: string;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};
